name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Code

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
        
    - name: Restore dependencies
      run: dotnet restore RecipeManager.sln
      
    - name: Build
      run: dotnet build RecipeManager.sln --no-restore
      
    - name: Test
      run: dotnet test RecipeManager.sln --no-build --verbosity normal
